name: Docker Build

on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  docker:
    runs-on: docker-full
    container:
      options: --privileged 
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Docker and BuildX
        run: |
          apt-get update
          apt-get install -y --no-install-recommends docker.io docker-buildx-plugin docker-compose

      - name: Set up Docker Buildx
        run: |
          docker buildx install
          docker buildx create --name ci-builder --use
          docker buildx inspect --bootstrap

      - name: Log in to Container Registry
        run: |
          echo "$PACKAGE_TOKEN" | docker login forge.engelmann.me -u "$PACKAGE_USER" --password-stdin
        env:
          PACKAGE_USER: ${{ secrets.PACKAGE_USER }}
          PACKAGE_TOKEN: ${{ secrets.PACKAGE_TOKEN }}

      - name: Build and push Docker image
        run: |
          BRANCH_NAME=${GITHUB_REF##*/}
          SHORT_SHA=${GITHUB_SHA:0:8}
          IMAGE_TAG="forge.engelmann.me/$GITHUB_REPOSITORY:${BRANCH_NAME}-${SHORT_SHA}"
          
          docker buildx build \
            --push \
            --platform linux/amd64 \
            --tag "$IMAGE_TAG" \
            --build-arg VERSION=${GITHUB_SHA} \
            --file ./transports/Dockerfile \
            .
